services:
    database:
        container_name: "postgres-dev"
        image: "postgres:16-alpine"
        env_file:
            - ../.env.development
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
